pycharmProjects/study/study/urls.py
from django.contrib import admin
from django.urls import path
from myproject import views,tem
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('login/', views.login),
    path('register/', views.register),
    path('logout/', views.logout),
    path('query/', views.query),
    # path('', tem.home.as_view()),

]

pycharmProjects/study/myproject/models.py
from django.db import models

# Create your models here.
class User(models.Model):

    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32, choices=gender, default="男")
    c_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"

pycharmProjects/study/myproject/views.py
from django.shortcuts import render,redirect,HttpResponse
from myproject import models
import pymysql
from django import forms
import json
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
def index(request):
    pass
    return render(request, 'myproject/index.html')


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username',None)
        password = request.POST.get('password',None)
        if username and password:
            username = username.strip()
            print(username,password)
            user = models.User.objects.filter(name__exact = username,password__exact = password)
            if user:
                return redirect('/index/')
            else:
                message = '用户名/密码不正确'
                return render(request, 'myproject/login.html',{'message':message})
        else:
            message = '账号或密码不能为空'
            return render(request, 'myproject/login.html', {'message': message})
    return render(request, 'myproject/login.html')

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username',None)
        password = request.POST.get('password',None)
        email = request.POST.get('email',None)
        sex = request.POST.get('sex',None)
        time = request.POST.get('time',None)
        print(username,password,email,sex,time)
        models.User.objects.create(name=username,password=password,email=email,sex=sex,c_time=time)
        return HttpResponse('注册成功')
    return render(request, 'myproject/register.html')


def logout(request):
    request.session.flush()
    return redirect("/login/")

conn = pymysql.connect(
    host="localhost",
    port=3306,
    user='root',
    password='123456',
    database="practice"
)
cursor = conn.cursor(cursor=pymysql.cursors.DictCursor)

class UserForm(forms.Form):
    sno = forms.CharField(label='学号',max_length=100,required=False)
    sname = forms.CharField(label='姓名',max_length=100,required=False)
    Aclass = forms.CharField(label='班级',max_length=100,required=False)

@csrf_exempt
def query(request):
    if request.method == 'POST':
        uf = UserForm(request.POST)
        if uf.is_valid():
            sno = uf.cleaned_data['sno']
            sname = uf.cleaned_data['sname']
            Aclass = uf.cleaned_data['Aclass']
            print(sno,sname,Aclass)
            sql = "select sno,sname,class as Aclass from students where sno like '%%%%%s%%%%' and " \
                  "sname like '%%%%%s%%%%' and class like '%%%%%s%%%%'"%(sno,sname,Aclass)
            print(sql)
            try:
                cursor.execute(sql)
                results = cursor.fetchall()
                results = json.dumps(results)
                print(results)
                return render(request, 'myproject/query.html', locals())
            except:
                print("Error: unable to fetch data")
    uf = UserForm()
    return render(request, 'myproject/query.html',locals())

pycharmProjects/study/myproject/templates/myproject/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.css' %}" rel="stylesheet">
      {% block css %}{% endblock %}

  </head>
  <body>
{#    <h1>你好，世界！</h1>#}
<nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
            <span class="sr-only">切换导航条</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Mysite</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/index/">主页</a></li>
            <li class="active"><a href="/query/">查询</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/login/">登录</a></li>
            <li><a href="/register/">注册</a></li>
              <li><a href="/logout/">退出</a></li>

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    {% block content %}{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

pycharmProjects/study/myproject/templates/myproject/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ pag_title }}</title>
</head>
<body>
{#    <h3>{{ global_env }}</h3>#}
    <select class="btn btn-logout" id="select_env">
        <option name="envpro" value="pro">生产环境</option>
        <option name="envpre" value="pre">预发环境</option>
        <option name="envtest" value="test">测试环境</option>
    </select>
<script src="/static/jquery.js"></script>
<script>
$("#select_env").change(function(){
    var value = $("#select_env").val();
    $.ajax({
        url:"/student/testapi",
        type:"GET",
        data:{env:value},
        dataType: 'json',
        success:function (result) {
            {#window.location.reload()#}
        }
    });
});
</script>
</body>
</html>

pycharmProjects/study/myproject/templates/myproject/index.html
{% extends 'myproject/base.html' %}
{% block title %}主页{% endblock %}
{% block content %}
    <h1>欢迎回来！</h1>
{% endblock %}

pycharmProjects/study/myproject/templates/myproject/login.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>登录</title>#}
{#</head>#}
{#<body>#}
{% extends 'myproject/base.html' %}
{% load static %}
{% block title %}登录{% endblock %}
{% block css %}<link href="{% static 'css/login.css' %}" rel="stylesheet"/>{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-login' action="/login/" method="post">
                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
              {% csrf_token %}
              <h2 class="text-center">欢迎登录</h2>
              <div class="form-group">
                <label for="id_username">用户名：</label>
                <input type="text" name='username' class="form-control" id="id_username" placeholder="Username" autofocus required>
              </div>
              <div class="form-group">
                <label for="id_password">密码：</label>
                <input type="password" name='password' class="form-control" id="id_password" placeholder="Password" required>
              </div>
              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>
          </form>
        </div>
    </div> <!-- /container -->
{% endblock %}
{#    <div style="margin: 15% 40%;">#}
{#        <h1>欢迎登录</h1>#}
{#        <form action="/login/" method="post">#}
{#            <p>#}
{#                <label for="id_username">用户名：</label>#}
{#                <input type="text" id="id_username" name="username" placeholder="用户名" autofocus required />#}
{#            </p>#}
{#            <p>#}
{#                <label for="id_password">密码：</label>#}
{#                <input type="password" id="id_password" placeholder="密码" name="password" required />#}
{#            </p>#}
{#            <input type="submit" value="确定">#}
{#        </form>#}
{##}
{#    </div>#}
{#</body>#}
{#</html>#}

pycharmProjects/study/myproject/templates/myproject/query.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询数据库</title>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
</head>
<body>
    <div>
        <form action="/query/" method="post">
            {% csrf_token %}
            {{ uf }}
            <button type="submit" id="query">查询</button>
            <button type="reset">重置</button>
        <table id="table" cellpadding="1" cellspacing="1" border="1">
            <caption align="top">学生信息</caption>
            <thead>
            <tr>
                <th>学号</th>
                <th>姓名</th>
                <th>班级</th>
            </tr>
            </thead>
            <tbody id="students"></tbody>
        </table>
    </form>
    </div>
</body>
<script>
    function student()
    {
        {#$.ajax#}
        {#({#}
        {#        type:"post",#}
			{#    url:"/query/",#}
			{#    data:"",#}
			{#    dataType:"json",#}
        {#        success:function(results) {#}
                    var results = {{ results|safe }};
                    console.log(results)
                    var obj = eval(results);
                    var tbody = $("#students");
                    $(obj).each(function (index) {
                        var val = obj[index];
                        console.log(val)
                        var tr = $('<tr></tr>');
                        tr.append('<td>' + val.sno + '</td>' + '<td>' + val.sname + '</td>' + '<td>' + val.Aclass + '</td>');
                        tbody.append(tr);
                    });
                    $('#table tbody').replaceWith(tbody);
        {#        }#}
        {#});#}
    }
    $(function()
    {
        student();
    })
</script>
</html>

pycharmProjects/study/myproject/templates/myproject/register.html
{% extends 'myproject/base.html' %}
{% load static %}
{% block title %}注册{% endblock %}
{% block content %}
    <div class="container">
        <form action="/register/" method="post">
            {% if message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
            {% csrf_token %}
            <p>
                <label for="id_username">用户名：</label>
                <input type="text" id="id_username" placeholder="用户名" name="username" autofocus required>
            </p>
            <p>
                <label for="id_password">密码：</label>
                <input type="password" id="id_password" name="password" placeholder="密码" required>
            </p>
            <p>
                <label for="id_email">邮箱：</label>
                <input type="email" id="id_email" name="email" placeholder="邮箱" required>
            </p>
            <p>
                <label for="id_sex">性别：</label>
                <select id="id_sex" name="sex">
                    <option value="男">男</option>
                    <option value="女">女</option>
                </select>
            </p>
            <p>
                <label for="id_ctime">日期：</label>
                <input type="datetime-local" id="id_ctime" name="time" placeholder="日期" required>
            </p>
            <button type="reset">重置</button>
            <button type="submit">提交</button>
        </form>
    </div>
{% endblock %}